### ISSUE TITLE
How are parallel programs generated?

### ISSUE THREAD

**Issue by Lysxia** [Quviq/QuickCheckExamples#2]
I'm wondering how [`crud_eqc.erl`](https://github.com/Quviq/QuickCheckExamples/blob/861d0768c9d8e353fecae4808d63b251a8c77362/src/crud_eqc.erl) generates parallel programs.

In particular, couldn't you generate one thread which updates a file, and another one which deletes it? Wouldn't an execution where the file is deleted before being updated cause a failure?

**Comment by Lysxia** [comment]
For context, I am trying to figure out [how to achieve a similar thing in quickcheck-state-machine](https://github.com/advancedtelematic/quickcheck-state-machine/issues/159#issuecomment-334783478), in Haskell.

**Comment by hanssv** [comment]
Without going into detail, parallel test cases are created from sequential test cases - this is done by splitting the single test case into several sequences to run in parallel. The splitting is done in "safe" way checking preconditions and interleavings, so we would not generate the case you mention.

**Comment by Lysxia** [comment]
Oh, that's interesting! Thank you!
